#import "@preview/isc-hei-bthesis:0.8.0": *
#import "@preview/acrostiche:0.7.0": *

#page-title("Résumé")

#v(1fr)

#reset-all-acronyms()

Tandis que les pipelines de #link("https://fr.wikipedia.org/wiki/Imagerie_par_r%C3%A9sonance_magn%C3%A9tique_fonctionnelle")[#acr("IRMf")] deviennent de plus en plus intensives sur le plan computationnel, nécessitant des calculs en haute dimension, il est crucial d'évaluer comment de petites variations numériques introduites par des facteurs tels que le #link("https://fr.wikipedia.org/wiki/Syst%C3%A8me_d%27exploitation")[#acr("OS")] utilisé, les stratégies de parallélisation et l'architecture matérielle affectent les résultats de ces pipelines.

S'appuyant sur le papier « Numerical Variability of #acr("IRMf") Graph Measures » #super[@Alizadeh2025.12.22.695524], ce travail reproduit l'analyse originale sur un ensemble de données multi-sites différent et étend l'évaluation au-delà des mesures de graphes. Il évalue l'impact du prétraitement fMRIPrep numériquement perturbé sur les matrices de #acr("CF") en utilisant le métrique du #acr("NPVR"), y compris l'effet de la régression du signal global, et examine les biomarqueurs du #link("https://fr.wikipedia.org/wiki/D%C3%A9pression_majeure")[#acr("TDM")], notamment ceux basés sur la #link("https://en.wikipedia.org/wiki/Principal_component_analysis")[#acr("PCA")] proposés par Yamashita et al., 2026 #super[#cite(label("10.1162/IMAG.a.1121"))].

Pour reproduire les conclusions de l'étude originale, les données ont été obtenues en exécutant le pipeline de prétraitement fMRIPrep #super[@fMRIPrep] (25.2.5) sur un ensemble de données multi-sites différent via un #link("https://hub.docker.com/r/madeinshinea/fuzzy-fmriprep", [conteneur Docker personnalisé]) avec des perturbations arithmétiques en virgule flottante introduites par  #link("https://github.com/verificarlo/verificarlo", "Verificarlo") #super[@denis2018verificarlocheckingfloatingpoint] et #link("https://github.com/verificarlo/fuzzy", "Fuzzy") #super[@greg_kiar_2026_20906259]. Après prétraitement, 15 facteurs de confusion au lieu de 6 ont été appliqués, car les données semblaient plus bruitées, et les matrices de #acr("CF") ont été obtenues à l'aide de Nilearn #super[@Nilearn] (0.13.1) avec différents seuils absolus appliqués. Les métriques de graphes ont ensuite été calculées à l'aide de NetworkX #super[@SciPyProceedings_11] (3.6.1).

L'évaluation des métriques de graphes a montré des tendances cohérentes, bien qu'avec des valeurs #acr("NPVR") plus élevées, et a révélé que l'application de plus de facteurs de confusion augmente le #acr("NPVR") ainsi que la variabilité de cet effet à travers les différents seuils. L'analyse au niveau des connexions individuelles des matrices de #acr("CF") a étendu ce travail en quantifiant le bruit numérique au niveau de chaque connexion et en comparant l'effet de l'inclusion et l'exclusion du facteur de confusion du signal global. Cette comparaison a révélé une variabilité substantielle (un #acr("NPVR") moyen d'environ 11% avec tous les facteurs de confusion), et a plus que doublé lorsque le facteur de confusion du signal global a été exclu.

La sélection de caractéristiques par #acr("PCA") a été appliquée aux ensembles de données SRPB et BMB complets plutôt qu'à une version subdivisée du SRPB uniquement comme dans l'étude originale. Pour évaluer sa stabilité numérique, deux étapes du pipeline ont été perturbées : le calcul des coefficients de corrélation à l'aide d'une #link("https://hub.docker.com/layers/verificarlo/fuzzy/v2.5.1-lapack-python3.12.13-numpy-scipy-sklearn/images/sha256-5fd0dff51fd585689ec2ab200c38f89c3cb58138a4604d41c92849ec8e619f5c", [image Docker Fuzzy spécifique]), et l'analyse en composantes principales en la forçant à utiliser des entrées en virgule flottante 32 bits plutôt que 64 bits.

Bien que les biomarqueurs spécifiques sélectionnés diffèrent entre les ensembles de données, ils proviennent systématiquement des mêmes régions cérébrales (réseaux préfrontaux, moteurs et sous-corticaux), leur importance relative variant toutefois. L'extraction de caractéristiques par #acr("PCA") s'est avérée très stable sous les perturbations numériques introduites, produisant des résultats strictement identiques pour toutes les exécutions perturbées au sein de chaque ensemble de données. Ces résultats suggèrent que l'extraction de caractéristiques par #acr("PCA") est non seulement stable entre différents sites d'imagerie et jeux de données, mais également robuste face à la variabilité numérique, soutenant ainsi sa fiabilité pour les applications cliniques.

#abstract-footer("fr")
